# allow mouse wheel
set -g mouse on

# Set both C-a and C-b as prefixes
set-option -g prefix C-a
set-option -g prefix2 C-b

# Optional: Allow C-a a to send prefix to application
bind-key C-a send-prefix

