#!/usr/bin/env bash
if [ -f ~/.bashlog ]; then . ~/.bashlog; else function bashlog() { :; }; fi

bashlog "sourcing custom bash_completions..."
for bcfile in ~/.config/bash_completion.d/* ; do
  bashlog "...sourcing $bcfile"
  . $bcfile
done
bashlog "done custom bash completions!"
