#!/usr/bin/env bash
if [ -f ~/.bashlog ]; then . ~/.bashlog; fi

log "sourcing custom bash_completions..."
for bcfile in ~/.config/bash_completion.d/* ; do
  log "...sourcing $bcfile"
  . $bcfile
done
log "done custom bash completions!"
